#!/usr/bin/env ruby

$: << File.expand_path(File.dirname(__FILE__) + '/../lib')

require 'debian/build'

platform = Debian::Build::Platform.find_by_name(ARGV.shift)
platform.pbuilder.exec :build, ARGV.shift
